'use client'
import { useEffect, useState } from 'react'
import { Loader2, Shield, Download, Trash2 } from 'lucide-react'
import { Card } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'

type Settings = { name: string; webEnrichmentEnabled: boolean; dataProcessingConsentAt: string | null; webSearch: { status: 'CONFIGURED' | 'UNAVAILABLE' | 'DISABLED'; label: string; provider?: string } }
export default function SettingsPage() {
  const [settings, setSettings] = useState<Settings | null>(null); const [saving, setSaving] = useState(false); const [confirmation, setConfirmation] = useState(''); const [message, setMessage] = useState('')
  async function load() { const response = await fetch('/api/settings'); if (response.ok) setSettings(await response.json() as Settings) }
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer) }, [])
  async function update(patch: { webEnrichmentEnabled?: boolean; consent?: boolean }) { setSaving(true); const response = await fetch('/api/settings', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(patch) }); if (response.ok) await load(); setSaving(false) }
  async function deleteData() { setSaving(true); const response = await fetch('/api/settings/delete-data', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ confirmation }) }); setMessage(response.ok ? 'Workspace contacts, conversations, imports, analyses, recommendations, evidence, feedback, and prior audit logs were deleted. The workspace and login remain.' : 'Deletion failed. Check the confirmation phrase.'); setSaving(false); if (response.ok) setConfirmation('') }
  return <div className="mx-auto max-w-4xl px-4 py-10"><div className="flex items-center gap-3"><Shield className="size-8 text-primary" /><div><h1 className="text-3xl font-semibold">Privacy & settings</h1><p className="text-muted-foreground">Control external processing and your stored pilot data.</p></div></div>
    {!settings ? <Loader2 className="mt-8 animate-spin" /> : <div className="mt-8 space-y-5"><Card className="p-5"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h2 className="font-semibold">Web enrichment</h2><p className="mt-1 text-sm text-muted-foreground">When enabled, general questions and selected target research may be sent to the configured search provider. Contact name, company, role, and location can be sent for bounded enrichment; email, phone, notes, and relationship history are not sent.</p><Badge className="mt-3" tone={settings.webSearch.status === 'CONFIGURED' ? 'success' : 'warning'}>{settings.webSearch.label}</Badge></div><label className="flex shrink-0 items-center gap-2 text-sm"><input type="checkbox" checked={settings.webEnrichmentEnabled} disabled={saving} onChange={(event) => void update({ webEnrichmentEnabled: event.target.checked })} />Enabled</label></div></Card>
      <Card className="p-5"><h2 className="font-semibold">Processing notice</h2><p className="mt-1 text-sm text-muted-foreground">Acknowledgement allows configured AI drafting to send a contact first name and, when available, role and company, plus the requested channel, tone, and your drafting instruction. Relationship history, notes, email, phone, evidence, scores, and recommendation reasoning are not sent.</p><Button className="mt-3" variant="outline" onClick={() => void update({ consent: !settings.dataProcessingConsentAt })}>{settings.dataProcessingConsentAt ? 'Withdraw acknowledgement' : 'Acknowledge notice'}</Button></Card>
      <Card className="p-5"><h2 className="font-semibold">Export contacts</h2><p className="mt-1 text-sm text-muted-foreground">Download the canonical records stored in this workspace.</p><div className="mt-3 flex gap-2"><Button variant="outline" onClick={() => { window.location.href = '/api/contacts/export?format=json' }}><Download />JSON</Button><Button variant="outline" onClick={() => { window.location.href = '/api/contacts/export?format=csv' }}><Download />CSV</Button></div></Card>
      <Card className="border-destructive/30 p-5"><h2 className="font-semibold text-destructive">Delete workspace data</h2><p className="mt-1 text-sm text-muted-foreground">This permanently deletes workspace contacts, interactions, edges, imports, conversations, conversation messages, analyses, evidence, recommendations, feedback, and earlier audit logs. The workspace, login, authentication settings, and privacy settings remain.</p><label className="mt-4 block text-sm font-medium">Type DELETE MY NETWORK<input value={confirmation} onChange={(event) => setConfirmation(event.target.value)} className="mt-1.5 h-10 w-full rounded-lg border bg-background px-3" /></label><Button className="mt-3" variant="destructive" disabled={confirmation !== 'DELETE MY NETWORK' || saving} onClick={() => void deleteData()}><Trash2 />Delete all workspace data</Button>{message && <p role="status" className="mt-3 text-sm">{message}</p>}</Card>
    </div>}
  </div>
}
